logging:
  level:
    root: INFO
    io.easyboard: DEBUG
    org.springframework:
      data.mongodb.core.MongoTemplate: DEBUG
      security: DEBUG

allowed_origin: http://localhost:3000
spring:
  data:
    mongodb:
      database: top-job-master
      uri: mongodb+srv://ofoe:B3lz1NQoP2CIJIvw@cluster0.0fbii.mongodb.net/?retryWrites=true&w=majority